### ISSUE TITLE
[BUG] - Auto-tunnel not working on 4.1.3

### ISSUE THREAD

**Issue by foux** [wgtunnel/wgtunnel#1038]
**Describe the bug**
On 4.1.3, connection detection works correctly (mobile datas, WiFi, WiFi name) but auto-tunnel doesn't, be it tunnel activation or deactivation

**Smartphone (please complete the following information):**

- Device: S25 Ultra
- Android Version: Android 16
- App Version 4.1.3
- App mode: VPN

**To Reproduce**

1. Setup auto-tunnel for mobile datas and unconfirmed WiFi network
2. Be on a confirmed WiFi network
3. Switch to mobile datas
4. The VPN doesn't turn on
5. Turn on VPN
6. Got to a confirmed WiFi
7. The VPN doesn't turn off

**Expected behavior**
Auto-tunnel should turn off and on the VPN according ro rules

**Screenshots (Only if necessary)**
Here is a video showing the errors
https://next.tfdn.cloud/s/b2bWSt6pCDA9HGR

**Comment by zer0fl0w** [comment]
confirmed. v4.1.3 has serious bug.
after update from 4.1.2 it toggles tunnel endlessly while not connecting to tunnel.

after fc and some app restarts it eventually connected to tunnel successfully.

what remains is that ssid does not get read anymore correctly. so autotunnel with trusted wifi connected does not disable tunnel anymore because ssid ist always "unknown".

tested and replicable on pixel 9a and pixel 7 with latest gos.

**Comment by zaneschepke** [comment]
Working on a fix for this now!

**Comment by OsakaRider** [comment]
Same, reverted to 4.1.2 for now

Also DO NOT restore a backup from 4.1.3 into 4.1.2, you will have the same issue and it wont even restore your configs

**Comment by asmj1108** [comment]
> confirmed. v4.1.3 has serious bug. after update from 4.1.2 it toggles tunnel endlessly while not connecting to tunnel.
> 
> after fc and some app restarts it eventually connected to tunnel successfully.
> 
> what remains is that ssid does not get read anymore correctly. so autotunnel with trusted wifi connected does not disable tunnel anymore because ssid ist always "unknown".
> 
> tested and replicable on pixel 9a and pixel 7 with latest gos.

A temporary workaround is to set the Wi-Fi detection method to "Legacy", the default method seems to have problem reading ssid

**Comment by foux** [comment]
> A temporary workaround is to set the Wi-Fi detection method to "Legacy"

This has absolutely nothing to do with the original issue. Please open a new one if you need.

**Comment by zaneschepke** [comment]
Just published a fix for this in the nightly. Can someone confirm this fixed the issue?

It seems to fix it for me. If we are all good, I'll publish a new release with this fix.

**Comment by zaneschepke** [comment]
This one should now be fixed in 4.1.4. Marking as closed for now.

**Comment by zer0fl0w** [comment]
v4.1.4 - standard ssid detection method is working again.

thanks for your quick support.

**Comment by zaneschepke** [comment]
> v4.1.4 - standard ssid detection method is working again.
> 
> thanks for your quick support.

Np! Sorry about the bug!

**Comment by Gothico74** [comment]
Still not working with 4.1.4.
Leaving home wlan gives me an error and tunnel collapses
![Screenshot_20251106-061000_1.png](https://github.com/user-attachments/assets/c1dc732a-87d2-4276-a8bd-dc01866114c6)

**Comment by Dola-Shuvi** [comment]
Can confirm the same issue as @Gothico74 in 4.1.4 . Manually restarting the tunnel a few times seemed to solve it for now, but it is a little inconvenient.

**Comment by zplan** [comment]
Can also confirm. Tunnel can not be established.
Fyi @zaneschepke

**Comment by OsakaRider** [comment]
Same here as well, it wont start it just connects and disconnects infinitely, reverted back to 4.1.1 its the only version that works perfectly for me

**Comment by zaneschepke** [comment]
Thanks for the reports. Looking into this.

**Comment by zaneschepke** [comment]
Any more details on steps to reproduce? Mode, tunnel details (domain or static ip, ipv4 only, ipv6 support, etc)?

**Comment by OsakaRider** [comment]
VPN mode with global override set, always on vpn is set in both the app and os setting, using auto tunnel on all settings except ethernet, wifi detection is set to default, but I don't have location settings on, I use auto tunnel to stop the vpn when I am outside without connection so I can use some of my apps offline. also debounce delay for me I set it to 1, but even the default 3 had this issue,

not sure about the domain or static thing, I am using a proton vpn config, and neither my isp or proton support ipv6 anyways

using a pixel 8 pro on the latest update which is october 2025. if there is a way to provide a log let me know

**Comment by zaneschepke** [comment]
> VPN mode with global override set, always on vpn is set in both the app and os setting, using auto tunnel on all settings except ethernet, wifi detection is set to default, but I don't have location settings on, I use auto tunnel to stop the vpn when I am outside without connection so I can use some of my apps offline. also debounce delay for me I set it to 1, but even the default 3 had this issue,
> 
> not sure about the domain or static thing, I am using a proton vpn config, and neither my isp or proton support ipv6 anyways
> 
> using a pixel 8 pro on the latest update which is october 2025. if there is a way to provide a log let me know

Thank you for these details! I'll try to reproduce now.

**Comment by zaneschepke** [comment]
I'm still unable to reproduce this, but I did find a related issue that might be the culprit. 

Could someone please give the latest nightly a try and see if that fixes the issue for you? It installs as a separate app.

**Comment by OsakaRider** [comment]
Latest nightly version connects successfully but unfortunately it doesnt stop when there is no internet like it should

**Comment by Dola-Shuvi** [comment]
> Any more details on steps to reproduce? Mode, tunnel details (domain or static ip, ipv4 only, ipv6 support, etc)?

VPN mode, domain with a dynamic IP but it doesn't change more than twice a month, dual stack support, 1360 MTU for client and server, 15 seconds keepalive, full tunnel, issue occurs in both Wi-Fi and mobile networks, tried Default and Shizuku network detection methods with the same outcome, debounce delay is set to 3.

Phone is a Google Pixel 8a on the latest Android 16 patches.

4.1.0 works flawlessly with this setup, anything after starts having issues after a while.


I'll give the latest nightly version a try and see if it helps.


**Edit:** 4.1.5 has been up and running for about an hour now with no issues. Will keep an eye on it for longer but it looks like it fixed the issue for me.

**Comment by zer0fl0w** [comment]
v4.1.5 - tunnel connection works for me.

BUT...with auto-tunnel enabled and trusted wifi set, this version does _not_ stop tunnel getting back from mobile network to wifi. i am connected to wifi, but wg tunnel still states mobile data under active network in auto tunnel tab.

this worked for me in v4.1.4. i personally had no problems with v4.1.4 on 3 devices. so for now v4.1.5 is a regression in my case.


_workaround to try for poeple with indefinitly tunnel reconnecting bug (which is not present for me anymore since v4.1.4) which i also described at the start of the thread and some also experienced here:
install a second vpn app for testing purposes, i.e. https://gitlab.torproject.org/tpo/applications/vpn/-/packages

connect to a vpn with another app than wg tunnel. 
disonnect again. than try wg tunnel again.
i could only stop the wg tunnel endlessly reconnecting bug with this method. tested on different pixels devices with gos_





thank you zane for you continious efforts!

**Comment by zaneschepke** [comment]
> v4.1.5 - tunnel connection works for me.
> 
> BUT...with auto-tunnel enabled and trusted wifi set, this version does _not_ stop tunnel getting back from mobile network to wifi. i am connected to wifi, but wg tunnel still states mobile data under active network in auto tunnel tab.

Thanks for these details. 

Does that Wi-Fi have an internet connection?

**Comment by zer0fl0w** [comment]
> Does that Wi-Fi have an internet connection?

yes, it does.

**Comment by zaneschepke** [comment]
> > Does that Wi-Fi have an internet connection?
> 
> yes, it does.

Thank you! I think I found the issue. I just released the fix in the latest nightly. Can you confirm the fix?

**Comment by zaneschepke** [comment]
> Latest nightly version connects successfully but unfortunately it doesnt stop when there is no internet like it should

So I've investigated this and this seems to be a "bug" in AndroidOS networking APIs. Even when mobile data has zero connectivity (and shows the '!') on mobile data, their APIs still return a "hopeful" connectivity and don't report the lack of connectivity and instead report as mobile data still being connected with internet connectivity 🤦 . Mobile data only reports as truly no connectivity when the interface is completely disabled. Their networking APIs are truly horrendous.

**Comment by zer0fl0w** [comment]
> Thank you! I think I found the issue. I just released the fix in the latest nightly. Can you confirm the fix?

CONFiRMED. nightly is fine! it works, at least for me!

well done!

**Comment by zaneschepke** [comment]
Thanks for the confirm. I'll cut a new release now.

**Comment by zaneschepke** [comment]
Closing this one out as it should be fixed in 4.1.6. If you're still having issues let me know and I'll reopen.
