### ISSUE TITLE
[FEATURE] - Add split tunnel package names manually for packages not detected by app

### ISSUE THREAD

**Issue by wingman1487** [wgtunnel/wgtunnel#750]
**Describe the bug**
For a time the "Galaxy Watch7 Manager" app showed up in the list of applications to Include / Exclude for Split Tunneling. For some reason that app no longer shows up in the list as something I can select, what having it there did was tunneled all of my Galaxy Watch internet traffic thru the Wireguard connection so I could use things like Home Assistant on my watch without the need for a VPN on the watch.

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 9 Pro XL
- Android Version: Android 15
- App Version: 3.8.1
- Backend: Userspace

**To Reproduce**

1. Go to Tunnel Settings
2. Click on "Split tunneling"
3. Scroll down OR Search for 'Galaxy Watch7 Manager'
4. Unable to find the application in the list

**Expected behavior**
I should be able to find and select the 'Galaxy Watch7 Manager' application from the list of Split Tunneling options so I can "Include" it and have my Galaxy Watch traffic included in the tunnel.

**Additional context**
If I select "All" the watch traffic is tunneled through Wireguard and I can control things like my Home Assistant instance through my watch when not on WiFi. However, if I "Exclude" and select _ALL_ the check boxes I am _STILL_ able to control Home Assistant through the Watch. It makes me think that the application is just hidden, and when I try to "Include", the small list of applications that I do want tunneled, I cannot find it, and my Watch traffic _DOES NOT_ go through the tunnel.

**Comment by zaneschepke** [comment]
Hello!

Did this by change occur after a system update? Most likely, Samsung is hiding this app now for whatever reason. You could also try to uninstall and reinstall the Watch app and see if that helps.

**Comment by wingman1487** [comment]
Ha, probably... Samsung is notorious for releasing highly disruptive often half baked "updates" to their devices. I noticed this issue when my watch started doing some different things and I reset it thinking it might fix it (sadly it didn't). I've also uninstalled and re-installed all the Samsung stuff on my phone with no joy, the Watch7 Manager just refuses to show up. Anyway we could have a custom field for package names?

**Comment by daterrell** [comment]
Just to add this seems really similar to #366 (as I think zaneschepke alluded to in [4](https://github.com/wgtunnel/wgtunnel/issues/750#issuecomment-2831220002) above), but also when enabling root via Magisk, _and_ using Insular, with WGTunnel in the work profile, the app IDs get munged.

E.g. in the work profile app ID is - say - 1050.  In the work profile, that same ID would be 101050.  With root it uses the owner app ID instead, so it's back to 1050 and is failed to be picked up by the `iptables --uid-owner`.  

I admit, haven't read the code and have _no clue_ how you do app ID resolution, but if the ID were reverse resolved from the name then it should be able to work in those cases.  (And now I'll stop suggesting solutions :heart: )

**Comment by zaneschepke** [comment]
I think this one should be fixed in the latest versions. 

The idea of adding custom packages won't work actually as it will cause the tunnel to fail if the package is not visible to the current profile. As for the Samsung issue, this might have been an issue with how I was filtering the queries of apps to have a launcher (which has since been changed). If this still isn't resolved let me know and we can reopen. 

As for the root issue, @daterrell, I think this might just be a quirk of root. I don't know that there is anything I can do on my end to prevent this from occurring.

**Comment by wingman1487** [comment]
@zaneschepke , Appreciate your continued development on the app, it's an amazing addition to my phone and contributes to my daily routine amazingly. Unfortunately on the latest version (4.1.1) the 'Galaxy Watch7 Manager' still doesn't show up in the application list. I still have the 'Galaxy Wearable' app that shows up, but that one isn't the right one. Happy to test anything out if you need!

**Comment by zaneschepke** [comment]
> [@zaneschepke](https://github.com/zaneschepke) , Appreciate your continued development on the app, it's an amazing addition to my phone and contributes to my daily routine amazingly. Unfortunately on the latest version (4.1.1) the 'Galaxy Watch7 Manager' still doesn't show up in the application list. I still have the 'Galaxy Wearable' app that shows up, but that one isn't the right one. Happy to test anything out if you need!

Thank you! I'll keep working hard to make it even better 😃 

If you exclude the app package manually in your conf file before importing, does it work and properly exclude the watch?

**Comment by wingman1487** [comment]
> Thank you! I'll keep working hard to make it even better 😃
> 
> If you exclude the app package manually in your conf file before importing, does it work and properly exclude the watch?

What I have noticed is if I copy the profile and set the Split Tunneling to the below...

### These work:
- **All**
- **Exclude** - And I select every package available in the list

### These don't work:
- **Include** - And I select every package available in the list

It's definitely there and I can reverse my way into pushing the watch traffic down (as well as my list of apps) by doing the **Exclude**, select all packages, and de-select the ones I actually want to send the data through the tunnel.

**Comment by zaneschepke** [comment]
> > Thank you! I'll keep working hard to make it even better 😃
> > If you exclude the app package manually in your conf file before importing, does it work and properly exclude the watch?
> 
> What I have noticed is if I copy the profile and set the Split Tunneling to the below...
> 
> ### These work:
> * **All**
> * **Exclude** - And I select every package available in the list
> 
> ### These don't work:
> * **Include** - And I select every package available in the list
> 
> It's definitely there and I can reverse my way into pushing the watch traffic down (as well as my list of apps) by doing the **Exclude**, select all packages, and de-select the ones I actually want to send the data through the tunnel.

Sorry, I'm not following. 

It seems like you're saying one of the apps listed is indeed the watch (although it is not obvious) because when you exclude all listed packages the watch is working again? Do I understand that correctly?

**Comment by wingman1487** [comment]
Sorry I may have not explained well. In all of these scenarios the "Galaxy Watch7 Manager" **is not visible** and does not show up in the list of applications. Let me put out an example and see if I can better define.

Example: I want to have this list of apps tunnel through WireGuard
- Home Assistant
- Chrome
- Galaxy Watch7 Manager

Create 1 tunnel and duplicate it 3 times, the only changes to each are the Split Tunneling config.

Tunnel 1 - Exclude
Tunnel 2 - Include
Tunnel 3 - All

### Tunnel 1 - Exclude
- All apps are selected in the Exclude list
- "Galaxy Watch7 Manager" is not available to select
- **Deselect** the other 2 (Home Assistant, Chrome)
I get the desired result and all 3 apps are routed through WireGuard, the watch **does** rout traffic through the tunnel

### Tunnel 2 - Include
- "Galaxy Watch7 Manager" is not available to select
- Select the other 2 (Home Assistant, Chrome)
Only the 2 apps selected route traffic through WireGuard, the watch **does not** route traffic though the tunnel

### Tunnel 3 - All
- Do nothing but select all
Everything including "Galaxy Watch7 Manager" is routed through the tunnel, the watch **does** rout traffic through the tunnel

With this I can tell that the WireGuard Tunnel is somehow aware of the "Galaxy Watch7 Manager"  even though it doesn't display it. Since I can exclude everything in "Tunnel 1 - Exclude" by selecting all the apps in the list and it still routes the watch traffic through the tunnel it's telling me that it's there in the background, but un-selectable, so WireGuard Tunnel doesn't know to explicitly exclude it, so it doesn't.  Same in the "Tunnel 3 - All" scenario, it routes the watch through the tunnel because it's aware of it somehow, but does not explicitly list it in the Include/Exclude lists.

Hope that helps and I didn't confuse it more.

**Comment by zaneschepke** [comment]
I've added a permission that will allow me to query all packages and now watch manager7 does show up in the list. Google will probably give me a little bit of a hard time for this permission, but I should be able to get it approved. 

This will be available in the next version and in the nightly tonight.
