### ISSUE TITLE
[BUG] - "Trusted wifi" recognition does not work when app in background 

### ISSUE THREAD

**Issue by pre97** [wgtunnel/wgtunnel#768]
**Describe the bug**
Wireguard tunnel is established after connecting to trusted wifi.

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S24 Ultra
- Android Version: 14
- App Version 3.9.0 (Google Playstore)

**To Reproduce**

1. Enable "Tunnel on untrusted wifi"
2. Add trusted wifi name for private wifi
3. Run app in background
4. Disable wifi
5. Enable wifi and connect to trusted wifi

**Screenshot**
![Screenshot_20250429_165148_Gallery.png](https://github.com/user-attachments/assets/dbcb4d16-ea13-4410-833a-2187fb559b62)

**Expected behavior**
There should be no tunnel connection after connecting with the trusted wifi.

**Comment by zaneschepke** [comment]
Hello! I'm unable to reproduce this. Does this fail every time or just sometimes?

Are there any other special characters/spacing in the name?

Also, are you sure you've properly matched the case and spacing on the name?

**Comment by pre97** [comment]
Hi Zane, thanks for your prompt response. It fails every time I connect to my private Wi-Fi while wgtunnel is running in the background. When the app is open, it works as intended. There are no special characters or spaces in the name, and the names match.

I will send you a screen recording showing both behaviors (app open vs. background) to your email. I hope this helps.

**Comment by maikatze** [comment]
Hi,
I could confirm the behavier discribben by pre97.
Smartphone:
Device: Samsung Galaxy S24 FE
Android Version: 14
App Version 3.9.1 (Google Playstore)

To Reproduce
Steps to reproduce the behavior:
Enable "Tunnel on untrusted wifi"
Add trusted wifi name for private wifi
Run app in background
Disable wifi
Enable wifi and connect to trusted wifi

MY SSID contains special characters/spaces
The problem occurs  by using the SSID name with escaped special characters (FRITZ\!Box\ 6360\ Cable), without escaped characters (FRITZ!Box 6360 Cable) and also by used wildcards (FRITZ*) or (FRITZ?Box?6360?Cable).

The tunnel will not disabled when trusted wifi is selected/enabled.

**Comment by mgzenitech** [comment]
I think you need to enable location permission to be always on ;)

**Comment by zaneschepke** [comment]
Yes, do you both have allow all the time location permission?

**Comment by maikatze** [comment]
For me:  Yes I have selected all the time location permission! 

![Image](https://github.com/user-attachments/assets/915cf439-2924-49d5-af7e-7ec3d224f139)

![Image](https://github.com/user-attachments/assets/322f12a8-95e0-40f4-981d-e5384916c8a5)

**Comment by Bram0172** [comment]
Same problem here! Location permission is granted all time. If disabled, it shows 'unkown SSID' under 'tunnel on untrusted wifi'.

Worked well until some weeks ago

**Comment by zaneschepke** [comment]
Is this only occurring on Samsung devices?

**Comment by Bram0172** [comment]
> Is this only occurring on Samsung devices?

I use a Xiaomi 12x, not a Samsung device.

**Comment by zaneschepke** [comment]
Is this issue still present on 3.9.1?

**Comment by maikatze** [comment]
Hi,
I have installed v3.9.1 and the problems are still present.

**Comment by Bram0172** [comment]
> Hi, I have installed v3.9.1 and the problems are still present.

Same here, on v3.9.1

**Comment by maikatze** [comment]
Please  find attached

[logcat_1747109513639.txt](https://github.com/user-attachments/files/20181127/logcat_1747109513639.txt)

**Comment by Bram0172** [comment]
Please find the files attached[

[wg_tunnel_logs-1747154362.zip](https://github.com/user-attachments/files/20192257/wg_tunnel_logs-1747154362.zip)

](url)

**Comment by pilovali** [comment]
I'd be happy to... but how?

**Comment by zaneschepke** [comment]
I fixed a bug that could also be contributing to this issue. 

Could someone please try 3.9.2 and see if it also resolved this issue?

**Comment by maikatze** [comment]
Hi,
Unfortunately no effekt.
Btw: could spaces in the SSID leads to the problem?

**Comment by Bram0172** [comment]
I have no spaces in my home network SSID

> Hi, Unfortunately no effekt. Btw: could spaces in the SSID leads to the problem?

**Comment by Bram0172** [comment]
3.9.2 not working.

Did try a fallback to 3.6.6 - works
Tried 3.7.0 - not working.

**Comment by Bram0172** [comment]
FYI: my wife uses a Samsung A55. The app works flawless at that device. So probably not specifically Samsung or Xiaomi related.

**Comment by pilovali** [comment]
> 3.9.2 not working.
> 
> Did try a fallback to 3.6.6 - works Tried 3.7.0 - not working.

I did the same. I didn't like the new place to enable/disable auto-tunnel anyway.

**Comment by kjabl** [comment]
I think I have a similar issue.
On autotunnel the tunnel isn't switched on correctly when my network changes. On WiFi and mobile data.

When I go to App-Info, force kill the app, start it again and toggle auto tunnel off and on again then it works for some time.

So I guess it could be connected to background topics.

**Comment by zaneschepke** [comment]
> 3.9.2 not working.
> 
> Did try a fallback to 3.6.6 - works Tried 3.7.0 - not working.

From 3.6.6 to 3.7.0 I switched the Android API I was using for getting Wi-Fi SSID information in order to limit the amount of location queries made. Unfortunately, this API is deprecated, but it is supposed to still work (it does on all of my devices). It seems that on some devices, this API no longer works properly. The way the new Android API works (which was being used in 3.6.6) is it queries location information on every Wi-Fi event, even if the network hasn't changed. This causes a lot of redundant location queries and the annoying location icon to appear in the system bar. The best fix for this is to probably add yet another setting where you can optionally opt into using the old API at your own risk.

**Comment by kjabl** [comment]
> > 3.9.2 not working.
> > 
> > Did try a fallback to 3.6.6 - works Tried 3.7.0 - not working.
> 
> From 3.6.6 to 3.7.0 I switched the Android API I was using for getting Wi-Fi SSID information in order to limit the amount of location queries made. Unfortunately, this API is deprecated, but it is supposed to still work (it does on all of my devices). It seems that on some devices, this API no longer works properly. The way the new Android API works (which was being used in 3.6.6) is it queries location information on every Wi-Fi event, even if the network hasn't changed. This causes a lot of redundant location queries and the annoying location icon to appear in the system bar. The best fix for this is to probably add yet another setting where you can optionally opt into using the old API at your own risk. 

A few days after my post here I switched to 3.9.2 fdroid flavor downloaded from GitHub which wasn't available in fdroid when I wrote my comment here. 

It's not perfect but a lot more stable now. Don't know if it's the version or if I'm just randomly lucky.

**Comment by Bram0172** [comment]
> > 3.9.2 not working.
> > Did try a fallback to 3.6.6 - works Tried 3.7.0 - not working.
> 
> From 3.6.6 to 3.7.0 I switched the Android API I was using for getting Wi-Fi SSID information in order to limit the amount of location queries made. Unfortunately, this API is deprecated, but it is supposed to still work (it does on all of my devices). It seems that on some devices, this API no longer works properly. The way the new Android API works (which was being used in 3.6.6) is it queries location information on every Wi-Fi event, even if the network hasn't changed. This causes a lot of redundant location queries and the annoying location icon to appear in the system bar. The best fix for this is to probably add yet another setting where you can optionally opt into using the old API at your own risk.

Happy to try a test build 😉

**Comment by zaneschepke** [comment]
Please give the latest nightly a try. Hopefully this fixes the issue: https://github.com/wgtunnel/wgtunnel/releases/tag/nightly

**Comment by Bram0172** [comment]
Tried 3.9.3. Not much of an improvement sadly.
- recognition of trusted wifi SSID is hit and miss. Shows actual SSID or 'unknown SSID' randomly on connection.
- seems to have difficulties to recognize connection or disconnection with mobile internet: on connection with SSID the label under 'tunnel with mobile data' keeps saying 'active'.

Could this be part of the problem? I think certain mobile phones (well, mine has) can keep mobile connection alive even when connected to wifi, for example to boost wifi speeds. But in my case, these setting is deactiveted in system settings.

**Comment by zaneschepke** [comment]
> Tried 3.9.3. Not much of an improvement sadly.
> 
> * recognition of trusted wifi SSID is hit and miss. Shows actual SSID or 'unknown SSID' randomly on connection.
> * seems to have difficulties to recognize connection or disconnection with mobile internet: on connection with SSID the label under 'tunnel with mobile data' keeps saying 'active'.
> 
> Could this be part of the problem? I think certain mobile phones (well, mine has) can keep mobile connection alive even when connected to wifi, for example to boost wifi speeds. But in my case, these setting is deactiveted in system settings.

First, thanks for testing this! So, what you are describing sounds like a permission issue. It seems it is getting the default "unknown ssid" while the app is backgrounded which typically points to a permissions issue. Can you confirm you have precise location enabled, and allow all the time location permission enabled?

Also, which device is this and android version? You said the recent app version works flawlessly on your wife's device, but not on yours? What is her android version?

**Comment by Bram0172** [comment]
![Image](https://github.com/user-attachments/assets/47db50f3-9b31-4c2f-85ce-aacaa427b33a)
![Image](https://github.com/user-attachments/assets/a7946665-49ce-4d7b-978f-a3299c581620)
![Image](https://github.com/user-attachments/assets/49824b9d-5327-4f4e-bd3e-7f6d2cc1b4f3)

**Comment by Bram0172** [comment]
Last attached image you can see both 'tunnel on mobile' and 'tunnel on untrusted wifi' (connected to my home network) active, wich I think should not or could not be active at the same time.

I use a Xiaomi 12X running Android 13. My partners device is a Samsung A55, running Android 14.

**Comment by zaneschepke** [comment]
> Last attached image you can see both 'tunnel on mobile' and 'tunnel on untrusted wifi' (connected to my home network) active, wich I think should not or could not be active at the same time.
> 
> I use a Xiaomi 12X running Android 13. My partners device is a Samsung A55, running Android 14.

Thanks for trying this and for these details. I found some issues with the changes I made that I think were causing these issues. I just released a new nightly version if you can give it a shot! Thanks again!

**Comment by Bram0172** [comment]
First, thanks for all your work and time making this app!

'Legacy' still gives the earlier mentioned flakey results, but using 'default' trusted wifi detection now works fine every time on my phone. So I think that's a fix.

I still have problems with the VPN reconnect between wifi and mobile internet:
- from using an untrusted wifi network switching to mobile internet by turning wifi off, works. Vice versa also: in all situations there's a VPN connection.
- from using my trusted wifi (home) network switching to mobile internet by turning wifi off, fails to start the VPN connection. The app shows both the trusted network still as 'active' (even though the wifi is turned off in the phone settings menu) and tunnel on mobile internet as 'active' at the same time.

**Comment by zaneschepke** [comment]
> First, thanks for all your work and time making this app!
> 
> 'Legacy' still gives the earlier mentioned flakey results, but using 'default' trusted wifi detection now works fine every time on my phone. So I think thats a fix.
> 
> I still have problems with the VPN reconnect between wifi and mobile internet:
> 
> * from using an untrusted wifi network switching to mobile internet by turning wifi of, works. Vice versa also: in all situations there's a VPN connection.
> * from using the trusted wifi network switching to mobile internet by turning wifi off, fails to start the VPN connection. The app shows the trusted network still as 'active', even though the wifi is turned off in the phone settings menu; and tunnel on mobile internet as 'active' at the same time.

Thanks for these details and for testing! I'm glad we found the root cause of the issue. The second issue you're experiencing is likely another bug somewhere. I'll investigate.

**Comment by TheGenuineGT** [comment]
> > Last attached image you can see both 'tunnel on mobile' and 'tunnel on untrusted wifi' (connected to my home network) active, wich I think should not or could not be active at the same time.
> > I use a Xiaomi 12X running Android 13. My partners device is a Samsung A55, running Android 14.
> 
> Thanks for trying this and for these details. I found some issues with the changes I made that I think were causing these issues. I just released a new nightly version if you can give it a shot! Thanks again!

Found this issue log yesterday and noticed the request to test nightly, also want to confirm that my issues of autotunneling off on trusted wifi appears to be resolved. Thanks for your hard work! I'll send you a ko-fi here soon!

**Comment by zaneschepke** [comment]
> First, thanks for all your work and time making this app!
> 
> 'Legacy' still gives the earlier mentioned flakey results, but using 'default' trusted wifi detection now works fine every time on my phone. So I think that's a fix.
> 
> I still have problems with the VPN reconnect between wifi and mobile internet:
> 
> * from using an untrusted wifi network switching to mobile internet by turning wifi off, works. Vice versa also: in all situations there's a VPN connection.
> * from using my trusted wifi (home) network switching to mobile internet by turning wifi off, fails to start the VPN connection. The app shows both the trusted network still as 'active' (even though the wifi is turned off in the phone settings menu) and tunnel on mobile internet as 'active' at the same time.

I think the main issue here is effectively resolved in 3.9.3. I'll mark this issue as closed. 

I was unable to reproduce the second issue you stated here. If you're still having this problem, please open a new ticket with the details and I can further investigate. Thanks again!
